# Generated by Django 4.0.5 on 2022-06-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categoryname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship.category'),
        ),
    ]
